# Generated by Django 2.2.2 on 2019-10-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbxapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('hash', models.CharField(max_length=64)),
            ],
        ),
    ]
